chore: upgrade typeorm
stelescuraul/rls pull request #49
Opened 2021-11-22 12:38 UTC by ahmadnazir

# Description

> Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Upgrading typeorm to `0.2.35` which comes with a few bug fixes: https://github.com/typeorm/typeorm/releases/tag/0.2.35

# Type of change

> Please select the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactor (non-breaking change which does not add functionality)

# Checklist:

- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2021-11-22 12:58 UTC, stelescuraul requested changes
Let's add a few tests to make sure that the relation loader is working fine with the RLS. 
Few tests that should cover selecting relations, with/without conditions as well

2021-11-22 12:58 UTC, stelescuraul commented on lib/common/RLSPostgresQueryRunner.ts
> +    useStructuredResult?: boolean,
This was the missing property that triggered the error ?

2021-11-22 12:59 UTC, ahmadnazir commented on lib/common/RLSPostgresQueryRunner.ts
> +    useStructuredResult?: boolean,
Yes.

2021-11-23 10:43 UTC, ahmadnazir commented
Closing in favor of https://github.com/Avallone-io/rls/pull/50

2021-11-23 10:43 UTC, closed without merging